import './globals.css';
import Navbar from './components/Navbar/index';
import Footer from './components/Footer/index';
import CallUsWidget from './components/CallUsWidget';

declare global {
  namespace JSX {
    interface IntrinsicElements {
      'call-us': any;
    }
  }
}

export const metadata = {
  title: 'Domainstacks',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
        <CallUsWidget />
      </body>
    </html>
  )
}
